name: carrot-mapper-dev-test

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  # next-client:
  #   image: carrot-next-client
  #   build:
  #     context: app/next-client-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - BACKEND_URL: http://web:8000
  #     - BACKEND_ORIGIN: "web:8000"
  #   # Mount the code directory
  #   volumes:
  #     - ./app/next-client-app:/app/next-client-app

  # workers:
  #   image: carrot-workers
  #   build:
  #     context: app/workers
  #     dockerfile: Dockerfile
  #   # This port was assumingly taken from https://learn.microsoft.com/en-us/azure/azure-functions/functions-deploy-container?tabs=acr%2Cbash%2Cazure-cli&pivots=programming-language-python
  #   ports:
  #     - 8080:80
  #   env_file:
  #     - local.settings.json
  #   # Mount the code directory
  #   volumes:
  #     - ./app/workers:/app/workers
  #   depends_on:
  #     - web

  # omop-lite:
  #   image: ghcr.io/andyrae/omop-lite
  #   volumes:
  #     - ./vocabs:/vocabs
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_PASSWORD: password
  #     - DB_NAME: omop

  web:
    image: carrot
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - $PWD/api:/api
    depends_on:
      - db
      - azurite
