name: carrot-mapper-dev-v2

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omop

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  next-client:
    image: carrot-next-client
    build:
      context: app/next-client-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://web:8000
      - BACKEND_ORIGIN="web:8000"
    volumes:
      - ./app/next-client-app:/app/next-client-app

  omop-lite:
    image: ghcr.io/andyrae/omop-lite
    volumes:
      - ./vocabs:/vocabs
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres
      - DB_NAME=omop

  web:
    image: carrot
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - NEXTJS_URL=http://next-client:3000
      - ALLOWED_HOSTS=['localhost', '127.0.0.1','web']
      - COCONNECT_DB_ENGINE=django.db.backends.postgresql
      - COCONNECT_DB_HOST=db
      - COCONNECT_DB_PORT=5432
      - COCONNECT_DB_NAME=omop
      - COCONNECT_DB_USER=postgres
      - COCONNECT_DB_PASSWORD=postgres
      - COCONNECT_DB_AUTH_TOKEN=
      - UPLOAD_ONLY=false
      - ENABLE_PROXY=true
      - CCOM_APP_URL=http://web:8000/
      - AZ_FUNCTION_USER=admin
      - DEBUG=True
      - NLP_QUEUE_NAME=nlpqueue-local
      - SCAN_REPORT_QUEUE_NAME=scanreports-local
      - UPLOAD_QUEUE_NAME=uploadreports-local
      - CREATE_CONCEPTS_QUEUE_NAME=conceptqueue-local
      - SECRET_KEY=secret
      - AZURE_ACCOUNT_NAME=devstoreaccount1
      - STORAGE_CONN_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    volumes:
      - ./app/api:/api
    depends_on:
      - db
      - azurite

  workers:
    image: carrot-workers
    build:
      context: app
      dockerfile: workers/Dockerfile
    ports:
      - 8080:80
    environment:
      - IsEncrypted=false
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=python
      - STORAGE_CONN_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - NLP_API_KEY=
      - APP_URL=http://web:8000/
      - AZ_FUNCTION_KEY=53756e8553c47897cebf6d6d730cf2e69ac4a46e
      - SCAN_REPORT_QUEUE_NAME=scanreports-local
      - NLP_QUEUE_NAME=nlpqueue-local
      - UPLOAD_QUEUE_NAME=uploadreports-local
      - CREATE_CONCEPTS_QUEUE_NAME=conceptqueue-local
      - RULES_QUEUE_NAME=rules-local
      - PAGE_MAX_CHARS=30000
      - CHUNK_SIZE=6
    volumes:
      - ./app/workers:/home/site/wwwroot
      - ./app/shared:/shared
    depends_on:
      - web
      - azurite
