version: '3.5'

services:

  api:
    build:
      dockerfile: ./docker/django/Dockerfile
      context: ./
    command: sh /entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./api:/api
      - ./data:/data
      - ./co-connect-tools:/coconnect
    ports:
      - "8080:8000"
      - "9999:9999"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5433:5432"

  redis:
    image: redis
    restart: unless-stopped

  celery_worker:
    build:
      dockerfile: ./docker/django/Dockerfile
      context: ./
    restart: unless-stopped
    command: celery -A api worker -l info
    env_file:
      - .env
    volumes:
      - ./api:/api
    depends_on:
      - api
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

