name: carrot-mapper-dev

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  next-client:
    image: carrot-next-client
    build:
      context: app/next-client-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://web:8000
      - BACKEND_ORIGIN=localhost:8000
    volumes:
      - ./app/next-client-app:/next-client-app

  omop-lite:
    image: ghcr.io/andyrae/omop-lite
    volumes:
      - ./vocabs:/vocabs
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

  web:
    image: carrot
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - NEXTJS_URL=http://next-client:3000
      - ALLOWED_HOSTS=['localhost', '127.0.0.1','web', 'workers']
      - COCONNECT_DB_ENGINE=django.db.backends.postgresql
      - COCONNECT_DB_HOST=db
      - COCONNECT_DB_PORT=5432
      - COCONNECT_DB_NAME=postgres
      - COCONNECT_DB_USER=postgres
      - COCONNECT_DB_PASSWORD=postgres
      - ENABLE_PROXY=true
      - AZ_FUNCTION_USER=admin
      - DEBUG=True
      - UPLOAD_QUEUE_NAME=uploadreports-local
      - SECRET_KEY=secret
      - AZURE_ACCOUNT_NAME=devstoreaccount1
      - AZ_URL=http://workers:80
      - AZ_RULES_NAME=RulesOrchestrator
      - AZ_RULES_EXPORT_QUEUE=rules=exports-local
      - STORAGE_CONN_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    volumes:
      - ./app/api:/api
    depends_on:
      - db
      - azurite

  workers:
    image: carrot-workers
    build:
      context: app
      dockerfile: workers/Dockerfile
    ports:
      - 8080:80
      - 7071:80
    environment:
      - IsEncrypted=false
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=python
      - STORAGE_CONN_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - APP_URL=http://web:8000/
      # The key below needed for authentication and can be obtained through localhost:8000/admin/ --> add tokens
      - AZ_FUNCTION_KEY=2d374a1f460fc9627d69e99c6cbeabf3f759d517
      - SCAN_REPORT_QUEUE_NAME=scanreports-local
      - NLP_QUEUE_NAME=nlpqueue-local
      - UPLOAD_QUEUE_NAME=uploadreports-local
      - CREATE_CONCEPTS_QUEUE_NAME=conceptqueue-local
      - RULES_QUEUE_NAME=rules-local
      - RULES_FILE_QUEUE_NAME=rules-file-local
      - PAGE_MAX_CHARS=30000
      - CHUNK_SIZE=6
      # The address that can be used to reach the function app from outside
      - WEBSITE_HOSTNAME=localhost:7071
    volumes:
      - ./app/workers:/home/site/wwwroot
      - ./app/shared:/shared
    depends_on:
      - web
      - azurite

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    volumes:
      - ./app/azurite:/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    command: azurite --blobHost azurite --queueHost azurite --tableHost azurite --location /data --debug /data/debug.log --loose --skipApiVersionCheck
    hostname: azurite
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==