version: '3.5'
services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5433:5432"
