name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER_ALLOW_RUNASROOT: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Make envfile
        run: |
          touch .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env 
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env 
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env 
          echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env 
          
          echo COCONNECT_DB_ENGINE=django.db.backends.postgresql >> .env  
          echo COCONNECT_DB_HOST=\${POSTGRES_HOST} >> .env  
          echo COCONNECT_DB_PORT=\${POSTGRES_PORT} >> .env  
          echo COCONNECT_DB_NAME=\${POSTGRES_DB} >> .env  
          echo COCONNECT_DB_USER=\${POSTGRES_USER} >> .env  
          echo COCONNECT_DB_PASSWORD=\${POSTGRES_PASSWORD} >> .env

          echo OMOP_POSTGRES_HOST=${{ OMOP_POSTGRES_HOST }} >> .env 
          echo OMOP_POSTGRES_USER=${{ OMOP_POSTGRES_USER }} >> .env  
          echo OMOP_POSTGRES_PASSWORD=${{ OMOP_POSTGRES_PASSWORD }} >> .env  
          echo OMOP_POSTGRES_PORT=${{ OMOP_POSTGRES_PORT }} >> .env  
          echo OMOP_POSTGRES_DB=${{ OMOP_POSTGRES_DB }} >> .env  
          
          echo PROJECT_NAME=api >> .env 
          cat .env
      - name: Build the docker-compose stack
        run: docker-compose build 
      - name: Run the dokcer-compose stack
        run: |
          #startup the stack
          docker-compose up -d
          #give it a minute to start properly
          sleep 1m
          #check the logs for errors
          if docker-compose logs | grep -i -q ERROR  ; then
              #print the errors before causing a fail
              docker-compose logs | grep -i ERROR
              echo "Errors found"
              exit 1
          else
             echo "No errors found!"
          fi
          #put the logs into a file
          docker-compose logs >> logs.out
          #shutdown the stack
          docker-compose down
      #save the logs so they can be further checked 
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: logs.out
          retention-days: 1
