name: Publish release images to Github Registry

# on:
#   release:
#     types: [released]
on:
  push:
    branches:
      - feat/863/add-release-workflow


env:
  app-name: carrot
  repo-owner: ${{ github.repository_owner }}
  registry: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Tag and build frontend
      - name: Extract frontend Docker metadata
        id: frontend_meta
        uses:  docker/metadata-action@v5.5.1
        with:
          images: ${{ env.registry }}/${{ env.repo-owner }}/${{ env.app-name }}/frontend

      - name: Build and push frontend image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./app/next-client-app
          file: ./app/next-client-app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.frontend_meta.outputs.tags }}

      # Tag and for backend
      - name: Extract backend Docker metadata
        id: backend_meta
        uses:  docker/metadata-action@v5.5.1
        with:
          images: ${{ env.registry }}/${{ env.repo-owner }}/${{ env.app-name }}/backend

      - name: Build and push backend image
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./app/Dockerfile.deploy
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.backend_meta.outputs.tags }}

      # Tag and for workers
      - name: Extract workers Docker metadata
        id: workers_meta
        uses:  docker/metadata-action@v5.5.1
        with:
          images: ${{ env.registry }}/${{ env.repo-owner }}/${{ env.app-name }}/workers

      - name: Build and push workers image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./app/workers
          file: ./app/workers/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.workers_meta.outputs.tags }}
